spring:
  application:
    name: springboot

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: validate
    properties:
      hibernate:
        "[format_sql]": true
    show-sql: true

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    org:
      springframework:
        security:
          web: TRACE

file:
  upload:
    path: springboot/upload
